services:
  - type: web
    name: visual-search-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: QDRANT_HOST
        value: qdrant.render-internal  # or your real IP if remote
      - key: QDRANT_PORT
        value: "6333"
    plan: free
